name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Run Azure PowerShell script
        uses: Azure/powershell@v1
        with:
          inlineScript: "$PSVersionTable"
          azPSVersion: latest
      
      - name: Run Azure PowerShell script 2
        uses: Azure/powershell@v1
        with:
          inlineScript: "Install-Module Az"
          azPSVersion: latest
